adds 'intro to greg' post
json-schema-org/blog pull request #14
Opened 2022-06-21 20:19 UTC by gregsdennis

I've joined Postman, too!

Depends on #13

2022-06-21 20:29 UTC, Julian commented
Nice! LGTM I think, post looks good! No nitpicks even.

2022-06-23 14:50 UTC, Relequestual requested changes
Can you change your images to be webp format please? They are super speedy =]
(https://github.com/json-schema-org/blog#requirements)

- [ ] Image format
- [ ] Update link to Julians article


Then I think it's good to go!

2022-06-24 12:38 UTC, Relequestual commented on pages/posts/and-then-there-were-three.md
> +JSON Schema has always been a passion project for me.  I didn't really see it at work\*, and I never had a problem for which JSON Schema was the solution.  Nevertheless, I recognized its potential th
ooooh. I made an assumption. My bad. Withdrawn.

2022-06-27 08:57 UTC, gregsdennis commented
Images fixed.  Link to Julian's post is correct as is.

2022-06-27 09:29 UTC, Relequestual approved these changes

2022-06-27 09:35 UTC, merged